name: app_storage
description: App local storage
version: 0.0.1+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2

dev_dependencies:
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
dependencies:
  shared_preferences: ^2.1.2
