name: popular_movies
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.7.0

dependencies:
  auto_route: ^10.0.1
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  json_annotation: ^4.8.1
  injectable: ^2.1.1
  intl: any
  shared_preferences: ^2.1.1
  cached_network_image: ^3.2.3
  google_fonts: ^6.2.1
  movies_api: ^0.0.1
  app_storage: ^0.0.1
  lottie: ^3.3.1

workspace:
  - packages/movies_api
  - packages/app_storage

dev_dependencies:
  auto_route_generator: ^10.0.1
  bloc_test: ^10.0.0
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.0
  mocktail: ^1.0.0
  very_good_analysis: ^7.0.0
  freezed: ^3.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/