include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.*.dart
  errors:
    invalid_annotation_target: ignore  

linter:
  rules:
    depend_on_referenced_packages: false    
    library_private_types_in_public_api: false
    use_build_context_synchronously: false
    public_member_api_docs: false
