name: movies_api
description: "Movies API to fetch data from TMDB API"
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  dio_cache_interceptor: ^3.5.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9
  very_good_analysis: ^7.0.0

